const fs = require('node:fs'), ts = require('typescript'), assert = require('node:assert/strict')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename)
const { boxFromEdges, cloneDetections } = require('../lib/floor-plan.ts')
const { rebuildRoomFloors } = require('../lib/floor-plan-repair.ts')
const { floorBoxes, floorAreaPx, overlapArea, roomWallFaces, applyScopedMaterial } = require('../lib/rooms.ts')
const { calculateBudget } = require('../lib/materials.ts')
const { parseProjectFile } = require('../lib/project-file.ts')
const item=(id,x1,y1,x2,y2,label='wall')=>({id,label,class_id:1,confidence:1,box:boxFromEdges(x1,y1,x2,y2)})
const size={width:200,height:200}
const shell=[item('top',20,20,180,30),item('bottom',20,170,180,180),item('left',20,30,30,170),item('right',170,30,180,170)]
const walls=[...shell,item('shared',95,30,105,170),item('branch',30,95,95,105)]
const legacy=[item('old-floor-a',20,20,175,175,'floor'),item('old-floor-b',25,25,180,180,'floor')]
const result=rebuildRoomFloors([...walls,...legacy],size)
const rooms=result.filter(d=>d.label==='floor')
assert.equal(rooms.length,3)
for(let i=0;i<rooms.length;i++) for(let j=i+1;j<rooms.length;j++) assert.equal(overlapArea(floorBoxes(rooms[i]),floorBoxes(rooms[j])),0)
assert.equal(rooms.reduce((a,r)=>a+floorAreaPx(r),0),17550)
const top=rooms.find(r=>r.box.x2<100&&r.box.y2<100), lower=rooms.find(r=>r.box.x2<100&&r.box.y1>100), right=rooms.find(r=>r.box.x1>100)
let painted=applyScopedMaterial(result,'floor','floor-oak','room',null,top.id,'positive')
assert.equal(painted.filter(d=>d.materialApplied).length,1)
painted=applyScopedMaterial(painted,'wall','wall-paint-white','room',null,top.id,'positive')
const shared=painted.find(d=>d.id==='shared')
assert.equal(shared.wallFinishes.length,1)
assert.equal(shared.wallFinishes[0].side,'negative')
assert.ok(shared.wallFinishes[0].end<0.5)
assert.equal(roomWallFaces(lower,shared)[0].side,'negative')
assert.equal(roomWallFaces(right,shared)[0].side,'positive')
painted=applyScopedMaterial(painted,'wall','wall-concrete','room',null,lower.id,'positive')
assert.equal(painted.find(d=>d.id==='shared').wallFinishes.length,2)
const beforeOpposite=structuredClone(painted.find(d=>d.id==='shared').wallFinishes)
painted=applyScopedMaterial(painted,'wall','wall-concrete','face','shared',null,'positive')
assert.deepEqual(painted.find(d=>d.id==='shared').wallFinishes.filter(f=>f.side==='negative'),beforeOpposite)
assert.equal(painted.find(d=>d.id==='shared').wallFinishes.filter(f=>f.side==='positive').length,1)
const budget=calculateBudget([painted.find(d=>d.id==='shared')],size,0.01,'')
const expected=140*0.01*2.8*(1+130/140)
assert.ok(Math.abs(budget.lines.reduce((n,l)=>n+l.quantity,0)-expected)<0.02)
const one=applyScopedMaterial(painted,'wall','wall-paint-white','selected','shared',null,'positive')
assert.equal(one.find(d=>d.id==='shared').wallFinishes.length,0)
const all=applyScopedMaterial(one,'wall','wall-paint-white','all',null,null,'positive')
assert.ok(all.filter(d=>d.label==='wall').every(d=>d.materialApplied&&d.wallFinishes.length===0))
assert.deepEqual(rebuildRoomFloors(painted,size),painted,'rebuild is idempotent and keeps stable room IDs and finishes')
const snapshot=cloneDetections(painted)
snapshot.find(d=>d.id===top.id).floorTiles[0].x1=0.001
assert.notDeepEqual(snapshot,painted)
const project={fileName:'test.png',fileType:'image/png',previewDataUrl:'data:image/png;base64,AA==',imageSize:size,detections:painted,metersPerPixel:0.01,updatedAt:1}
assert.deepEqual(parseProjectFile(JSON.stringify({format:'sketch2spec',version:1,project})).detections,painted)
const concave=rebuildRoomFloors([...shell,item('notch-v',95,30,105,105),item('notch-h',30,95,105,105)],size).filter(d=>d.label==='floor')
assert.equal(concave.length,2)
const l=concave.find(r=>r.floorTiles.length>1)
assert.ok(l)
assert.ok(floorAreaPx(l)<l.box.width*l.box.height)
assert.equal(overlapArea(floorBoxes(l),[boxFromEdges(30,30,95,95)]),0,'L-room does not cover neighbouring room inside its bounding box')
assert.deepEqual(rebuildRoomFloors([shell[0],...legacy],size),[shell[0],...legacy],'no enclosure preserves existing work')
console.log('PASS: three rooms; no floor overlap; shared-wall sides and intervals; per-room/floor/face/all scopes; area budget; stable rebuild; deep undo snapshot; backup roundtrip; L-room concavity; open-room preservation')
const { introducesFloorOverlap } = require('../lib/rooms.ts')
assert.equal(introducesFloorOverlap(result,result),false)
assert.equal(introducesFloorOverlap(result,[...result,item('duplicate-room',30,30,90,90,'floor')]),true)
const translated=result.map(d=>d.id===top.id?{...d,box:boxFromEdges(80,30,145,95)}:d)
assert.equal(introducesFloorOverlap(result,translated),true)
assert.equal(introducesFloorOverlap([...walls,...legacy],[...walls,...legacy]),false,'unchanged legacy geometry can still be repainted')
console.log('PASS: adding or moving floors cannot introduce overlap; unchanged legacy geometry remains repairable')

// Non-grid-aligned, subpixel walls: floors must meet every inner face exactly.
const fractional=walls.map(d=>({...d,box:boxFromEdges(d.box.x1*6.13+.27,d.box.y1*6.13+.19,d.box.x2*6.13+.27,d.box.y2*6.13+.19)}))
const exact=rebuildRoomFloors(fractional,{width:1400,height:1400})
const exactRooms=exact.filter(d=>d.label==='floor')
assert.equal(exactRooms.length,3)
for(const r of exactRooms) for(const f of roomWallFaces(r,fractional[4])) {
  const parts=floorBoxes(r)
  assert.ok(parts.some(b=>Math.abs((f.side==='negative'?b.x2:b.x1)-(f.side==='negative'?fractional[4].box.x1:fractional[4].box.x2))<1e-8))
}
assert.ok(Math.abs(exactRooms.reduce((a,r)=>a+floorAreaPx(r),0)-17550*6.13**2)<1e-6)
const thin=item('thin',100,0,100.5,200), thinRoom=item('thin-room',20,20,100,90,'floor')
thinRoom.roomBoundaryTolerancePx=10
assert.deepEqual(roomWallFaces(thinRoom,thin).map(f=>f.side),['negative'])
const hitPaint=applyScopedMaterial(result,'wall','wall-concrete','face','shared',null,'negative',.2)
assert.equal(hitPaint.find(d=>d.id==='shared').wallFinishes.length,1)
assert.ok(hitPaint.find(d=>d.id==='shared').wallFinishes[0].end<.5)
assert.equal(applyScopedMaterial(result,'wall','wall-concrete','face','shared',null,'negative',.5).find(d=>d.id==='shared').wallFinishes,undefined)
const {removeDuplicateOpenings}=require('../lib/floor-plan-repair.ts')
const openings=[item('door',40,20,65,30,'door'),{...item('duplicate',41,20,65,30,'window'),confidence:.6},item('adjacent',70,20,90,30,'window'),item('parallel',40,32,65,42,'door')]
assert.deepEqual(removeDuplicateOpenings(openings).map(d=>d.id),['door','adjacent','parallel'])
const swing=rebuildRoomFloors([...shell,item('swing',65,15,85,45,'door')],size).find(d=>d.label==='floor')
assert.equal(floorAreaPx(swing),140*140)
console.log('PASS: fractional floors touch walls; thin walls cannot paint opposite side; clicked spans stop at next room; duplicate openings removed; door symbols do not carve floor gaps')
assert.equal(applyScopedMaterial(result,'wall','wall-concrete','face','shared',null,'negative').find(d=>d.id==='shared').wallFinishes,undefined)
console.log('PASS: ambiguous multi-room wall face requires selecting a room span before painting')
