const fs = require('node:fs')
const ts = require('typescript')
const assert = require('node:assert/strict')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename)
const { SCG_PRODUCTS } = require('../lib/scg-catalog.ts')
const { MATERIALS, calculateBudget } = require('../lib/materials.ts')

assert.ok(SCG_PRODUCTS.length >= 10 && SCG_PRODUCTS.length <= 25)
assert.deepEqual(new Set(SCG_PRODUCTS.map(product => product.target)), new Set(['floor','wall','door','window','ceiling']))
assert.equal(new Set(SCG_PRODUCTS.map(product => product.id)).size, SCG_PRODUCTS.length)
for (const product of SCG_PRODUCTS) {
  assert.ok(product.sourceUrl.startsWith('https://'))
  assert.ok(!Number.isNaN(Date.parse(product.lastCheckedAt)))
  assert.ok(product.brand && product.productName && product.category)
  assert.equal(product.currency, 'THB')
  assert.ok(!product.referencePrice || (product.priceMin === undefined && product.priceMax === undefined))
  assert.ok(product.priceMin === undefined || product.priceMin <= product.priceMax)
  assert.equal(MATERIALS.find(material => material.id === product.id)?.product, product)
}
const ixpe = SCG_PRODUCTS.find(product => product.sku === 'SPIX111')
assert.deepEqual(ixpe.dimensions, {widthMm:183,lengthMm:1220,thicknessMm:5})
assert.equal(ixpe.piecesPerPackage, 10)
assert.equal(ixpe.coveragePerPackageM2, 2.2326)
assert.equal(SCG_PRODUCTS.find(product => product.id === 'scg-smartboard-groove3').priceMin, 52)
assert.equal(SCG_PRODUCTS.find(product => product.id === 'scg-smartboard-groove3').priceMax, 69.5)
const floor = {id:'floor',label:'floor',box:{x1:0,y1:0,x2:100,y2:100,width:100,height:100},materialId:ixpe.id,materialApplied:true}
const budget = calculateBudget([floor], {width:100,height:100}, .02, '')
assert.equal(budget.lines.length, 1)
assert.equal(budget.lines[0].unitPrice, null, 'missing product price must not become a fabricated zero price')
assert.equal(budget.lines[0].total, null)
assert.equal(budget.subtotal, 0)
console.log('PASS: 12 sourced SCG catalog records cover five targets; verified package and price-range samples; missing price stays unavailable')
